const portfolioOptions = [
  { value: 'Growth', label: 'Growth' },
  { value: 'Platform', label: 'Platform' },
  { value: 'Trust', label: 'Trust' },
];

const programOptions = [
  { value: 'Revenue Acceleration', label: 'Revenue Acceleration' },
  { value: 'Operations Core', label: 'Operations Core' },
  { value: 'Experience Modernization', label: 'Experience Modernization' },
  { value: 'Trust Platform', label: 'Trust Platform' },
];

const healthOptions = [
  { value: 'GREEN', label: 'Green' },
  { value: 'AMBER', label: 'Amber' },
  { value: 'RED', label: 'Red' },
];

const riskSeverityOptions = [
  { value: 'LOW', label: 'Low' },
  { value: 'MEDIUM', label: 'Medium' },
  { value: 'HIGH', label: 'High' },
  { value: 'CRITICAL', label: 'Critical' },
];

const workstreamOptions = [
  { value: 'Checkout', label: 'Checkout' },
  { value: 'Growth Ops', label: 'Growth Ops' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Supply Chain', label: 'Supply Chain' },
  { value: 'Controls', label: 'Controls' },
  { value: 'Evidence', label: 'Evidence' },
  { value: 'Identity', label: 'Identity' },
  { value: 'Workspace', label: 'Workspace' },
  { value: 'Insights', label: 'Insights' },
  { value: 'Data', label: 'Data' },
  { value: 'AppSec', label: 'AppSec' },
  { value: 'Platform', label: 'Platform' },
  { value: 'Planning', label: 'Planning' },
  { value: 'Analytics', label: 'Analytics' },
  { value: 'Partner Ops', label: 'Partner Ops' },
  { value: 'Enablement', label: 'Enablement' },
];

const readinessOptions = [
  { value: 'READY', label: 'Ready' },
  { value: 'WATCH', label: 'Watch' },
  { value: 'BLOCKED', label: 'Blocked' },
];

export const executiveCommandCenterSpec = {
  id: 'executive-command-center',
  title: 'Executive Command Center',
  version: '2.0',
  layout: 'twoColumn',
  layoutOptions: { columnGap: '18px', rowGap: '14px' },
  dataSources: {
    initiatives: { name: 'initiatives', query: 'initiatives', delivery: { mode: 'paginatedList', pageSize: 6 } },
    initiativesVisual: { name: 'initiativesVisual', query: 'initiativesVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    initiativesSummary: { name: 'initiativesSummary', query: 'initiativesSummary', delivery: { mode: 'summary' } },
    roadmapVisual: { name: 'roadmapVisual', query: 'roadmapVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    workItemsSummary: { name: 'workItemsSummary', query: 'workItemsSummary', delivery: { mode: 'summary' } },
    risksVisual: { name: 'risksVisual', query: 'risksVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
  },
  filters: [
    {
      type: 'select',
      id: 'portfolio',
      label: 'Portfolio',
      dataSource: ['initiatives', 'initiativesVisual', 'initiativesSummary', 'roadmapVisual', 'workItemsSummary', 'risksVisual'],
      options: portfolioOptions,
      paramKey: 'portfolio',
    },
    {
      type: 'multiSelect',
      id: 'health',
      label: 'Health',
      dataSource: ['initiatives', 'initiativesVisual', 'initiativesSummary'],
      options: healthOptions,
      paramKey: 'health',
    },
    {
      type: 'search',
      id: 'initiativeSearch',
      label: 'Initiative focus',
      dataSource: ['initiatives', 'initiativesVisual'],
      groupIds: ['overview-focus'],
      paramKey: 'search',
      placeholder: 'Search initiative, sponsor, or theme',
    },
    {
      type: 'numericRange',
      id: 'signalScore',
      label: 'Signal score',
      dataSource: ['initiativesVisual', 'initiativesSummary'],
      groupIds: ['signal-tab'],
      paramKeyFrom: 'scoreFrom',
      paramKeyTo: 'scoreTo',
      min: 0,
      max: 100,
      step: 5,
    },
    {
      type: 'dateRange',
      id: 'deliveryWindow',
      label: 'Roadmap window',
      dataSource: 'roadmapVisual',
      groupIds: ['execution-tab'],
      paramKeyFrom: 'endFrom',
      paramKeyTo: 'endTo',
    },
  ],
  groups: [
    { id: 'overview-focus', label: 'Overview focus', widgetIds: ['ecc-portfolio-count', 'ecc-spend-kpi', 'ecc-program-cards'] },
  ],
  presets: [
    {
      id: 'growth-watch',
      label: 'Growth watchlist',
      filterState: { portfolio: 'Growth', health: ['AMBER', 'RED'], signalScore: { from: 50, to: 90 } },
    },
    {
      id: 'trust-momentum',
      label: 'Trust momentum',
      filterState: { portfolio: 'Trust', health: ['GREEN', 'AMBER'] },
    },
  ],
  tabs: [
    { id: 'overview-tab', label: 'Overview', widgetIds: ['ecc-portfolio-count', 'ecc-spend-kpi', 'ecc-program-cards', 'ecc-risk-doughnut'] },
    { id: 'signal-tab', label: 'Signal Map', widgetIds: ['ecc-score-bar', 'ecc-value-scatter'] },
    { id: 'execution-tab', label: 'Execution', widgetIds: ['ecc-roadmap-trend', 'ecc-work-kpi'] },
  ],
  widgets: [
    {
      type: 'kpi',
      id: 'ecc-portfolio-count',
      title: 'Active initiatives',
      dataSource: 'initiativesSummary',
      groupIds: ['overview-focus'],
      config: { valueKey: 'count', label: 'Portfolio initiatives', format: 'number', trend: { dataKey: 'trendScore' } },
    },
    {
      type: 'kpi',
      id: 'ecc-spend-kpi',
      title: 'Actual spend',
      dataSource: 'initiativesVisual',
      groupIds: ['overview-focus'],
      config: {
        valueKey: 'spendActual',
        aggregation: { op: 'sum', key: 'spendActual' },
        label: 'Filtered spend',
        format: 'currency',
        currencyCode: 'USD',
        decimalPlaces: 0,
      },
    },
    {
      type: 'cardView',
      id: 'ecc-program-cards',
      title: 'Program cards',
      dataSource: 'initiatives',
      groupIds: ['overview-focus'],
      config: {
        titleKey: 'name',
        subtitleKey: 'program',
        badges: [{ key: 'health', label: 'Health' }, { key: 'phase', label: 'Phase' }],
        metadata: [
          { key: 'owner', label: 'Owner' },
          { key: 'strategicTheme', label: 'Theme' },
          { key: 'endDate', label: 'End date' },
          { key: 'summary', label: 'Narrative' },
        ],
        primaryMetric: {
          key: 'completionPercent',
          label: 'Complete',
          format: 'number',
          decimalPlaces: 0,
          suffix: '%',
        },
        conditionalFormatting: [
          {
            target: { type: 'card' },
            when: { field: 'health', op: 'eq', value: 'RED' },
            tone: 'danger',
            label: 'Red initiative',
          },
          {
            target: { type: 'card' },
            when: { field: 'completionPercent', op: 'lt', value: 60 },
            tone: 'warning',
            label: 'Low completion',
          },
        ],
        template: 'detailed',
      },
      width: '100%',
    },
    {
      type: 'doughnutChart',
      id: 'ecc-risk-doughnut',
      title: 'Risk exposure by severity',
      dataSource: 'risksVisual',
      config: { categoryKey: 'severity', valueKey: 'exposure' },
      height: '280px',
    },
    {
      type: 'barChart',
      id: 'ecc-score-bar',
      title: 'Signal score by initiative',
      dataSource: 'initiativesVisual',
      groupIds: ['signal-tab'],
      config: { categoryKey: 'name', valueKey: 'score' },
      height: '300px',
    },
    {
      type: 'scatterChart',
      id: 'ecc-value-scatter',
      title: 'Spend vs. forecast value',
      dataSource: 'initiativesVisual',
      groupIds: ['signal-tab'],
      config: { xKey: 'spendActual', yKey: 'forecastValue', zKey: 'confidence' },
      height: '300px',
    },
    {
      type: 'lineChart',
      id: 'ecc-roadmap-trend',
      title: 'Roadmap completion over milestone dates',
      dataSource: 'roadmapVisual',
      groupIds: ['execution-tab'],
      config: { categoryKey: 'milestoneDate', valueKey: 'completionPercent' },
      height: '280px',
    },
    {
      type: 'kpi',
      id: 'ecc-work-kpi',
      title: 'Ready work items',
      dataSource: 'workItemsSummary',
      groupIds: ['execution-tab'],
      config: { valueKey: 'readyCount', label: 'Ready now', format: 'number', trend: { dataKey: 'trendPercentComplete' } },
    },
  ],
};

export const deliveryTimelineStudioSpec = {
  id: 'delivery-timeline-studio',
  title: 'Delivery Timeline Studio',
  layout: 'twoColumn',
  layoutOptions: { columnGap: '20px', rowGap: '16px' },
  dataSources: {
    roadmapVisual: { name: 'roadmapVisual', query: 'roadmapVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    roadmapItems: { name: 'roadmapItems', query: 'roadmapItems', delivery: { mode: 'paginatedList', pageSize: 10 } },
    initiativesVisual: { name: 'initiativesVisual', query: 'initiativesVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
  },
  filters: [
    { type: 'select', id: 'program', label: 'Program', dataSource: ['roadmapVisual', 'roadmapItems', 'initiativesVisual'], options: programOptions, paramKey: 'program' },
    { type: 'multiSelect', id: 'workstream', label: 'Workstream', dataSource: ['roadmapVisual', 'roadmapItems'], options: workstreamOptions, paramKey: 'workstream' },
    { type: 'dateRange', id: 'startWindow', label: 'Schedule start', dataSource: ['roadmapVisual', 'roadmapItems'], paramKeyFrom: 'startFrom', paramKeyTo: 'startTo' },
    { type: 'search', id: 'timelineSearch', label: 'Roadmap search', dataSource: ['roadmapVisual', 'roadmapItems'], paramKey: 'search', placeholder: 'Search initiative or roadmap item' },
  ],
  sections: [
    { id: 'studio-summary', title: 'Schedule Summary', widgetIds: ['dts-throughput-kpi', 'dts-timeline'] },
    { id: 'studio-detail', title: 'Sequencing Detail', widgetIds: ['dts-gantt', 'dts-roadmap-table'] },
  ],
  widgets: [
    {
      type: 'kpi',
      id: 'dts-throughput-kpi',
      title: 'Average roadmap completion',
      dataSource: 'roadmapVisual',
      config: {
        valueKey: 'completionPercent',
        aggregation: { op: 'avg', key: 'completionPercent' },
        label: 'Average completion',
        format: 'number',
        decimalPlaces: 0,
        suffix: '%',
      },
    },
    {
      type: 'timelineView',
      id: 'dts-timeline',
      title: 'Roadmap timeline',
      dataSource: 'roadmapVisual',
      config: {
        startDateKey: 'startDate',
        endDateKey: 'endDate',
        labelKey: 'name',
        groupKey: 'initiativeName',
        statusKey: 'status',
      },
      height: '320px',
    },
    {
      type: 'ganttChart',
      id: 'dts-gantt',
      title: 'Workstream gantt',
      dataSource: 'roadmapVisual',
      config: {
        startDateKey: 'startDate',
        endDateKey: 'endDate',
        labelKey: 'name',
        groupKey: 'workstream',
        statusKey: 'health',
      },
      height: '320px',
    },
    {
      type: 'table',
      id: 'dts-roadmap-table',
      title: 'Roadmap by initiative',
      dataSource: 'roadmapItems',
      config: {
        groupByKey: 'initiativeName',
        groupLabelKey: 'initiativeName',
        columns: [
          { key: 'name', label: 'Roadmap item' },
          { key: 'workstream', label: 'Workstream' },
          { key: 'status', label: 'Status' },
          { key: 'startDate', label: 'Start', type: 'date' },
          { key: 'endDate', label: 'End', type: 'date' },
          { key: 'dependencyRisk', label: 'Dependency risk' },
        ],
      },
      width: '100%',
    },
  ],
};

export const portfolioSignalMapSpec = {
  id: 'portfolio-signal-map',
  title: 'Portfolio Signal Map',
  layout: 'twoColumn',
  dataSources: {
    initiativesVisual: { name: 'initiativesVisual', query: 'initiativesVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    initiativesSummary: { name: 'initiativesSummary', query: 'initiativesSummary', delivery: { mode: 'summary' } },
    risksVisual: { name: 'risksVisual', query: 'risksVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
  },
  filters: [
    { type: 'select', id: 'portfolio', label: 'Portfolio', dataSource: ['initiativesVisual', 'initiativesSummary', 'risksVisual'], options: portfolioOptions, paramKey: 'portfolio' },
    { type: 'multiSelect', id: 'health', label: 'Health', dataSource: ['initiativesVisual', 'initiativesSummary'], options: healthOptions, paramKey: 'health' },
    { type: 'numericRange', id: 'signalScore', label: 'Signal score', dataSource: ['initiativesVisual', 'initiativesSummary'], paramKeyFrom: 'scoreFrom', paramKeyTo: 'scoreTo', min: 0, max: 100, step: 5 },
  ],
  widgets: [
    {
      type: 'kpi',
      id: 'psm-confidence-kpi',
      title: 'Average confidence',
      dataSource: 'initiativesSummary',
      config: { valueKey: 'avgConfidence', label: 'Confidence index', format: 'number', decimalPlaces: 0, trend: { dataKey: 'trendScore' } },
    },
    {
      type: 'doughnutChart',
      id: 'psm-portfolio-doughnut',
      title: 'Forecast value by portfolio',
      dataSource: 'initiativesVisual',
      config: { categoryKey: 'portfolio', valueKey: 'forecastValue' },
      height: '280px',
    },
    {
      type: 'spiralChart',
      id: 'psm-theme-spiral',
      title: 'Strategic theme signal',
      dataSource: 'initiativesVisual',
      config: { categoryKey: 'strategicTheme', valueKey: 'score' },
      height: '280px',
    },
    {
      type: 'scatterChart',
      id: 'psm-value-scatter',
      title: 'Spend vs. value',
      dataSource: 'initiativesVisual',
      config: { xKey: 'spendActual', yKey: 'forecastValue', zKey: 'confidence' },
      height: '300px',
    },
    {
      type: 'bubbleChart',
      id: 'psm-risk-bubble',
      title: 'Risk concentration map',
      dataSource: 'risksVisual',
      config: { xKey: 'likelihood', yKey: 'impact', zKey: 'exposure', labelKey: 'initiativeName', seriesKey: 'severity' },
      height: '300px',
    },
  ],
};

export const operationsDeepDiveSpec = {
  id: 'operations-deep-dive',
  title: 'Operations Deep Dive',
  layout: 'singleColumn',
  dataSources: {
    workItemsVisual: { name: 'workItemsVisual', query: 'workItemsVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    workItemsSummary: { name: 'workItemsSummary', query: 'workItemsSummary', delivery: { mode: 'summary' } },
    roadmapVisual: { name: 'roadmapVisual', query: 'roadmapVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
  },
  filters: [
    { type: 'select', id: 'portfolio', label: 'Portfolio', dataSource: ['workItemsVisual', 'workItemsSummary', 'roadmapVisual'], options: portfolioOptions, paramKey: 'portfolio' },
    { type: 'select', id: 'readiness', label: 'Readiness', dataSource: ['workItemsVisual', 'workItemsSummary'], options: readinessOptions, paramKey: 'readiness' },
    { type: 'dateRange', id: 'targetWindow', label: 'Target window', dataSource: 'workItemsVisual', paramKeyFrom: 'targetFrom', paramKeyTo: 'targetTo' },
  ],
  widgets: [
    {
      type: 'kpi',
      id: 'odd-blocked-kpi',
      title: 'Blocked points',
      dataSource: 'workItemsSummary',
      config: { valueKey: 'blockedPointsTotal', label: 'Blocked effort', format: 'number' },
    },
    {
      type: 'table',
      id: 'odd-work-item-table',
      title: 'Execution by workstream',
      dataSource: 'workItemsVisual',
      config: {
        groupByKey: 'workstream',
        groupLabelKey: 'workstream',
        columns: [
          { key: 'name', label: 'Work item' },
          { key: 'initiativeName', label: 'Initiative' },
          { key: 'readiness', label: 'Readiness' },
          { key: 'priority', label: 'Priority' },
          { key: 'blockedPoints', label: 'Blocked points' },
          { key: 'completionPercent', label: 'Completion %' },
          { key: 'targetDate', label: 'Target', type: 'date' },
        ],
        aggregations: [
          { key: 'blockedPoints', op: 'sum' },
          { key: 'completionPercent', op: 'avg' },
        ],
        groupAggregations: [
          { key: 'blockedPoints', op: 'sum' },
          { key: 'completionPercent', op: 'avg' },
        ],
        groupSummaryLabel: 'Workstream subtotal',
        grandTotalLabel: 'Portfolio total',
        sort: [
          { key: 'blockedPoints', direction: 'desc' },
          { key: 'targetDate', direction: 'asc' },
        ],
        drillDown: {
          urlTemplate: '/ops/{id}',
          paramKeys: ['id'],
          target: '_blank',
        },
        conditionalFormatting: [
          {
            target: { type: 'row' },
            when: { field: 'readiness', op: 'eq', value: 'BLOCKED' },
            tone: 'danger',
            label: 'Blocked work item',
          },
          {
            target: { type: 'cell', columnKey: 'blockedPoints' },
            when: { field: 'blockedPoints', op: 'gt', value: 20 },
            tone: 'warning',
            label: 'High blocked effort',
          },
          {
            target: { type: 'cell', columnKey: 'completionPercent' },
            when: { field: 'completionPercent', op: 'lt', value: 50 },
            tone: 'info',
            label: 'Low completion',
          },
        ],
      },
    },
    {
      type: 'table',
      id: 'odd-roadmap-summary-table',
      title: 'Roadmap summary roll-up',
      dataSource: 'roadmapVisual',
      config: {
        groupByKey: 'initiativeName',
        groupLabelKey: 'initiativeName',
        summary: [
          { key: 'name', op: 'count' },
          { key: 'endDate', op: 'latest' },
          { key: 'dependencyRisk', op: 'max' },
          { key: 'status', op: 'distinct' },
        ],
        sort: { key: 'dependencyRisk', direction: 'desc' },
      },
    },
  ],
};

export const riskAndReadinessReviewSpec = {
  id: 'risk-and-readiness-review',
  title: 'Risk And Readiness Review',
  layout: 'twoColumn',
  dataSources: {
    risks: { name: 'risks', query: 'risks', delivery: { mode: 'paginatedList', pageSize: 8 } },
    risksVisual: { name: 'risksVisual', query: 'risksVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    risksSummary: { name: 'risksSummary', query: 'risksSummary', delivery: { mode: 'summary' } },
    workItemsVisual: { name: 'workItemsVisual', query: 'workItemsVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    workItemsSummary: { name: 'workItemsSummary', query: 'workItemsSummary', delivery: { mode: 'summary' } },
  },
  filters: [
    { type: 'select', id: 'portfolio', label: 'Portfolio', dataSource: ['risks', 'risksVisual', 'risksSummary', 'workItemsVisual', 'workItemsSummary'], options: portfolioOptions, paramKey: 'portfolio' },
    { type: 'multiSelect', id: 'severity', label: 'Severity', dataSource: ['risks', 'risksVisual', 'risksSummary'], groupIds: ['risk-focus'], options: riskSeverityOptions, paramKey: 'severity' },
    { type: 'select', id: 'readiness', label: 'Readiness', dataSource: ['workItemsVisual', 'workItemsSummary'], groupIds: ['readiness-focus'], options: readinessOptions, paramKey: 'readiness' },
    { type: 'numericRange', id: 'exposure', label: 'Exposure', dataSource: ['risks', 'risksVisual', 'risksSummary'], groupIds: ['risk-focus'], paramKeyFrom: 'exposureFrom', paramKeyTo: 'exposureTo', min: 0, max: 100, step: 5 },
  ],
  groups: [
    { id: 'risk-focus', label: 'Risk focus', widgetIds: ['rrr-critical-kpi', 'rrr-risk-stack', 'rrr-risk-pie', 'rrr-risk-table'] },
    { id: 'readiness-focus', label: 'Readiness focus', widgetIds: ['rrr-ready-kpi', 'rrr-readiness-funnel'] },
  ],
  sections: [
    { id: 'rrr-summary', title: 'Headline Signals', widgetIds: ['rrr-critical-kpi', 'rrr-ready-kpi'] },
    { id: 'rrr-visuals', title: 'Visual Review', widgetIds: ['rrr-risk-stack', 'rrr-risk-pie', 'rrr-readiness-funnel'] },
    { id: 'rrr-register', title: 'Risk Register', widgetIds: ['rrr-risk-table'] },
  ],
  widgets: [
    {
      type: 'kpi',
      id: 'rrr-critical-kpi',
      title: 'Critical risks',
      dataSource: 'risksSummary',
      groupIds: ['risk-focus'],
      config: { valueKey: 'criticalCount', label: 'Critical items', format: 'number', trend: { dataKey: 'trendExposure' } },
    },
    {
      type: 'kpi',
      id: 'rrr-ready-kpi',
      title: 'Ready work items',
      dataSource: 'workItemsSummary',
      groupIds: ['readiness-focus'],
      config: { valueKey: 'readyCount', label: 'Ready to move', format: 'number', trend: { dataKey: 'trendPercentComplete' } },
    },
    {
      type: 'stackedBarChart',
      id: 'rrr-risk-stack',
      title: 'Likelihood vs impact by initiative',
      dataSource: 'risksVisual',
      groupIds: ['risk-focus'],
      config: {
        categoryKey: 'initiativeName',
        series: [
          { key: 'likelihood', label: 'Likelihood' },
          { key: 'impact', label: 'Impact' },
        ],
      },
      height: '300px',
    },
    {
      type: 'pieChart',
      id: 'rrr-risk-pie',
      title: 'Exposure by status',
      dataSource: 'risksVisual',
      groupIds: ['risk-focus'],
      config: { categoryKey: 'status', valueKey: 'exposure' },
      height: '280px',
    },
    {
      type: 'funnelChart',
      id: 'rrr-readiness-funnel',
      title: 'Readiness funnel',
      dataSource: 'workItemsVisual',
      groupIds: ['readiness-focus'],
      config: { categoryKey: 'readiness', valueKey: 'effortPoints' },
      height: '280px',
    },
    {
      type: 'table',
      id: 'rrr-risk-table',
      title: 'Risk register',
      dataSource: 'risks',
      groupIds: ['risk-focus'],
      config: {
        columns: [
          { key: 'title', label: 'Risk' },
          { key: 'initiativeName', label: 'Initiative' },
          { key: 'severity', label: 'Severity' },
          { key: 'status', label: 'Status' },
          { key: 'exposure', label: 'Exposure' },
          { key: 'reviewDate', label: 'Review', type: 'date' },
        ],
      },
      width: '100%',
    },
  ],
};

export const programNarrativeBoardSpec = {
  id: 'program-narrative-board',
  title: 'Program Narrative Board',
  layout: 'twoColumn',
  layoutOptions: { columnGap: '24px', rowGap: '18px' },
  dataSources: {
    initiatives: { name: 'initiatives', query: 'initiatives', delivery: { mode: 'paginatedList', pageSize: 4 } },
    initiativesSummary: { name: 'initiativesSummary', query: 'initiativesSummary', delivery: { mode: 'summary' } },
    initiativesVisual: { name: 'initiativesVisual', query: 'initiativesVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    roadmapItems: { name: 'roadmapItems', query: 'roadmapItems', delivery: { mode: 'paginatedList', pageSize: 6 } },
    roadmapVisual: { name: 'roadmapVisual', query: 'roadmapVisual', delivery: { mode: 'fullVisual', maxRows: 200 } },
    risksSummary: { name: 'risksSummary', query: 'risksSummary', delivery: { mode: 'summary' } },
  },
  filters: [
    { type: 'select', id: 'program', label: 'Program', dataSource: ['initiatives', 'initiativesSummary', 'initiativesVisual', 'roadmapItems', 'roadmapVisual', 'risksSummary'], options: programOptions, paramKey: 'program' },
    { type: 'search', id: 'storySearch', label: 'Narrative focus', dataSource: ['initiatives', 'roadmapItems'], paramKey: 'search', placeholder: 'Search themes, roadmap items, or narratives' },
  ],
  sections: [
    { id: 'pnb-opening', title: 'Opening Frame', widgetIds: ['pnb-initiative-count', 'pnb-progress-kpi', 'pnb-story-cards'] },
    { id: 'pnb-momentum', title: 'Momentum', widgetIds: ['pnb-momentum-area', 'pnb-roadmap-cards'] },
    { id: 'pnb-watchouts', title: 'Watchouts', widgetIds: ['pnb-risk-kpi'] },
  ],
  widgets: [
    {
      type: 'kpi',
      id: 'pnb-initiative-count',
      title: 'Programs in motion',
      dataSource: 'initiativesSummary',
      config: { valueKey: 'count', label: 'Initiatives', format: 'number' },
      width: '50%',
    },
    {
      type: 'kpi',
      id: 'pnb-progress-kpi',
      title: 'Average completion',
      dataSource: 'initiativesSummary',
      config: { valueKey: 'avgCompletionPercent', label: 'Completion', format: 'number', decimalPlaces: 0, suffix: '%' },
      width: '50%',
    },
    {
      type: 'cardView',
      id: 'pnb-story-cards',
      title: 'Executive story cards',
      dataSource: 'initiatives',
      config: {
        titleKey: 'name',
        subtitleKey: 'strategicTheme',
        badges: [{ key: 'health', label: 'Health' }, { key: 'status', label: 'Status' }],
        metadata: [
          { key: 'owner', label: 'Owner' },
          { key: 'program', label: 'Program' },
          { key: 'summary', label: 'Story' },
        ],
        primaryMetric: {
          key: 'forecastValue',
          label: 'Value',
          format: 'currency',
          currencyCode: 'USD',
          decimalPlaces: 0,
        },
        template: 'detailed',
      },
      width: '100%',
    },
    {
      type: 'areaChart',
      id: 'pnb-momentum-area',
      title: 'Roadmap momentum',
      dataSource: 'roadmapVisual',
      config: { categoryKey: 'milestoneDate', valueKey: 'completionPercent' },
      height: '280px',
    },
    {
      type: 'cardView',
      id: 'pnb-roadmap-cards',
      title: 'Roadmap moments',
      dataSource: 'roadmapItems',
      config: {
        titleKey: 'name',
        subtitleKey: 'initiativeName',
        badges: [{ key: 'workstream', label: 'Workstream' }, { key: 'stage', label: 'Stage' }],
        metadata: [
          { key: 'owner', label: 'Owner' },
          { key: 'milestoneDate', label: 'Milestone' },
          { key: 'narrative', label: 'Narrative' },
        ],
        primaryMetric: {
          key: 'dependencyRisk',
          label: 'Dependency risk',
          format: 'number',
          decimalPlaces: 0,
        },
        template: 'compact',
      },
      width: '100%',
    },
    {
      type: 'kpi',
      id: 'pnb-risk-kpi',
      title: 'Open exposure',
      dataSource: 'risksSummary',
      config: { valueKey: 'openExposure', label: 'Open exposure', format: 'number', trend: { dataKey: 'trendExposure' } },
    },
  ],
};

export const starterReports = [
  { id: 'executive-command-center', label: 'Executive Command Center', spec: executiveCommandCenterSpec },
  { id: 'delivery-timeline-studio', label: 'Delivery Timeline Studio', spec: deliveryTimelineStudioSpec },
  { id: 'portfolio-signal-map', label: 'Portfolio Signal Map', spec: portfolioSignalMapSpec },
  { id: 'operations-deep-dive', label: 'Operations Deep Dive', spec: operationsDeepDiveSpec },
  { id: 'risk-and-readiness-review', label: 'Risk And Readiness Review', spec: riskAndReadinessReviewSpec },
  { id: 'program-narrative-board', label: 'Program Narrative Board', spec: programNarrativeBoardSpec },
];
